import { Roboto } from "next/font/google";
import "./globals.css";

// thêm font
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
  variable: "--font-roboto",
  display: "swap",
});

// metadata sẽ phải bỏ export type ra vì JS không hỗ trợ
export const metadata = {
  title: "Task Zeen",
  description: "Generated by create next app",
  icons: [{ rel: "icon", type: "image/png", url: "/logo2.png" }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
